version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/vendor/bundle
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true